import Head from "next/head";
import {
  AboutUs,
  CallToAction,
  Contact,
  FAQ,
  Footer,
  Header,
  Hero,
  Portifolio,
  Services,
  Team,
} from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Devlayer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Services />
      <AboutUs />
      <CallToAction />
      <Portifolio />
      <Team />
      <Contact />
      <Footer />
    </>
  );
}
